### ISSUE TITLE
Implement Passive Voice / General Grammar Linter

### ISSUE THREAD

**Issue by Samyoul** [status-im/specs#134]
With the implementation of https://github.com/status-im/specs/pull/132 this repo needs an automated method of alerting contributors that a change they've made introduces use of the passive voice.

I've done some research and [LanguageTool](https://github.com/languagetool-org/languagetool) has the ability to scan text and highlight this kind of grammatical analysis. Language also has the ability to check for other complex grammatical errors, such as, improper use of the infinitive, missing articles, incorrect use of "too" and "to", incorrect use of "then" and "than", etc.

I have no experience implementing CI checks and tools, could I ask for guidance from the infra master @jakubgs and keeper of the specs @decanus?

Is LanguageTool the kind of thing that could be easily integrated into CI?

**Comment by jakubgs** [comment]
I general you'd ran a bot to talk to GitHub, like this one for example:
https://github.com/status-im/status-github-bot

Those bots - also known as GitHub Apps - work by exposing an HTTP endpoint - a webhook - that gets called by GitHub on specific events:
https://developer.github.com/webhooks/
You can see the different types of events that a webhook can be triggered on here:
https://developer.github.com/webhooks/event-payloads/

Here's an example of how that's done in Node.js:
https://blog.scottlogic.com/2017/05/22/gifbot-github-integration.html
I'd assume you can write the same thing in Java, which is what the LanguageTool is developed in. Or alternatively write it in JS as a wrapper around LanguageTool.

**Comment by jakubgs** [comment]
An alternative, if we want to just make a wrapper around LanguageTool - would be to simply add that functionality to `status-github-bot` as yet another module.

Not ideal, but would be marginally simpler, since I don't really know how its auth works, so I'd have to figure that out.
