### ISSUE TITLE
[Message Payload] Describe the format of replies/citations 

### ISSUE THREAD

**Issue by adambabik** [status-im/specs#22]
In the client, it's possible to reply to someone's message. Is this a part of the protocol at all? If so, we need to describe how it works in https://github.com/status-im/specs/blob/master/x8.md#replies.

**Comment by oskarth** [comment]
@status-im/clojure

**Comment by cammellos** [comment]
That's already specified https://github.com/status-im/specs/blob/master/status-payloads-spec.md `response-to` , the current develop branch is using `response-to-v2`, but the plan was to change it back to `response-to` as we don't need to be backward compatible anymore.
cc @corpetty
