### ISSUE TITLE
Spec template

### ISSUE THREAD

**Issue by oskarth** [status-im/specs#26]
We should have a standard format of specs so they are easier to read and parse.

Here's one example that's fairly clean https://github.com/status-im/bigbrother-specs/blob/master/data_sync/mvds.md#table-of-contents

Wdyt @status-im/status-protocol

**Comment by oskarth** [comment]
Also see https://github.com/status-im/specs/issues/1

This issue is slightly more narrow in scope, as it only deals with the individual spec format. More formal process can come later.

**Comment by corpetty** [comment]
I like the MVDS spec format, personally. We can get nitpicky once
everything is in such a state.

Corey

**Comment by oskarth** [comment]
Done I believe
