### ISSUE TITLE
Document device based communication and negotiation

### ISSUE THREAD

**Issue by oskarth** [status-im/specs#32]
With this we can do things like protocol negotiation. This was developed as part of topic partitioning.

Need to figure out specifics for how it'd work with something like MVDS too

**Comment by corpetty** [comment]
@cammellos I'm assuming https://github.com/status-im/specs/commit/494d0a74bbd20bc82a95d1bdebc696fb4f9d2b26 was meant to close this?

**Comment by cammellos** [comment]
If we are happy with it, it can be closed

**Comment by corpetty** [comment]
will close for now, open something new if needed.
