### ISSUE TITLE
Document workings of private groups

### ISSUE THREAD

**Issue by kdeme** [status-im/specs#48]
Unless I'm missing something, the workings of private groups chats and `group-user-message` are not really described.

It is mentioned at https://github.com/status-im/specs/blob/master/status-payloads-spec.md#message-types

And at https://github.com/status-im/specs/blob/master/status-secure-transport-spec.md#messaging it is said that private group chat can  be reduced to 1:1 chat. But it would be good to have more detail on how exactly.

**Comment by oskarth** [comment]
@cammellos is this still relevant / ongoing? If not, can we unassign and explicitly deprio/write then it will be attacked?

cc @corpetty

**Comment by cammellos** [comment]
This should be done https://github.com/status-im/specs/blob/master/status-group-chats-spec.md

**Comment by oskarth** [comment]
@kdeme does above solve your issue?

**Comment by kdeme** [comment]
Yeah it does. Great, thanks!
