### ISSUE TITLE
Fix Whisper usage spec wrt mailserver

### ISSUE THREAD

**Issue by oskarth** [status-im/specs#55]
As a client implementer, I want specs to describe how to use mailservers, not how the Status app works.

## Right now
Currently this spec: https://github.com/status-im/specs/blob/master/status-whisper-usage-spec.md#request-historic-messages explains the boring / non protocoly part: status-react to status go.

## Expected

Instead, it should explain the interface between status-go and mailservers. Specifically:

"The above topics is then converted into a bloom filter and then and sent to the Mailserver." should be expanded on, and the "Object - The message request object:  [...]" part from status-react should probably be removed.

^ @adambabik @corpetty

**Comment by adambabik** [comment]
@oskarth

> and the "Object - The message request object: [...]" part from status-react should probably be removed.

This is not related to status-react but it's a definition of a JSON-RPC API to send a request for historic messages. I think this is crucial to be specified so that clients can use any Whisper implementation they want.

**Comment by oskarth** [comment]
Ok, that's fine. As long as it is clear how you actually implement mailserver/client support for a different implementation. Right now this isn't too clear IMO.

cc @kdeme @decanus
