### ISSUE TITLE
Document added Whisper packet codes

### ISSUE THREAD

**Issue by adambabik** [status-im/specs#58]
We would like to document all Whisper packet codes that extend EIP-627 so that other implementation can be complete in terms of feature set.

### Acceptance criteria

1. Determine which packet codes present in [our Whisper fork](https://github.com/status-im/whisper) are actively used.
2. Document used packet codes with their purpose.

### References

- Discussion started in https://github.com/status-im/specs/pull/54#discussion_r342635703.

**Comment by oskarth** [comment]
Any update on this @adambabik? Would be good to get in Waku

Also cc @decanus

**Comment by adambabik** [comment]
I think we have all packet codes covered now. The only thing is message confirmations which we haven't discussed yet and there is no notion of message confirmation in Waku/0 spec.

**Comment by oskarth** [comment]
Where? There's an issue but no associated PR, yet you say it is "all covered".

Also if you are working on it, please assign yourself and mark it as TODO/WIP (or done if it is (?))

**Comment by adambabik** [comment]
@oskarth sorry, we covered that for the Waku spec but not here. I will list all packet codes in https://github.com/status-im/specs/blob/master/status-whisper-usage-spec.md. There is no single place in this document that summaries packet codes.
