### ISSUE TITLE
Document additional parameters in the Whisper handshake

### ISSUE THREAD

**Issue by adambabik** [status-im/specs#59]
We would like to document the additional parameters in the Whisper handshake added in the protocol.

### Acceptance criteria

1. Describe all additional parameters present in the Whisper handshake in [our fork of Whisper](https://github.com/status-im/whisper).

### References

- Discussion started in https://github.com/status-im/specs/pull/54#discussion_r342635703.

**Comment by oskarth** [comment]
@adambabik @kdeme @decanus what's state of this? Would be good if we can finish this up and ensure Waku handshake is documented properly

**Comment by adambabik** [comment]
It's been covered in https://github.com/status-im/specs/pull/60 as a separate section `Handshake`.
