### ISSUE TITLE
Replace forked Whisper usage with Waku/0 in specs

### ISSUE THREAD

**Issue by oskarth** [status-im/specs#61]
# Problem
Currently we use a forked version of Whisper that isn't documented in any great detail. This makes it difficult for other clients to implement and get compatibility with Status clients, e.g. status-nim. It also creates confusion around what requirements and guarantees we have, since we are de facto doing more than EIP627 and this has implications around UX, privacy, DDoS resistance, etc (mailservers, light node, rate limiting).

# Acceptance criteria

* [ ] Status Client spec reference Waku spec
* [ ] Updated Waku mode usage spec (replace Whisper Usage and Mailserver)

As well as issues/dependencies marked out for for :

* [x] Current specs for v1 marked clearly as such
* [ ] Deprecation/recommendation notice for Waku mode for client implementers (e.g. status-nim)

# Details
See https://github.com/vacp2p/specs/issues/27 for more details.

This issue is largely dependent on above, but some work can be done in parallel to ease that work. I.e. by documenting customization to Whisper in our current specs, such as:

* [x] mailserver usage
* [x] light mode
* [x] extra packet codes
* [x] rate limiting
* [x] any other changes we have done to EIP627 that aren't accurately captured in our specs (litmus test: 100% compatibility with status-nim w/o reading status-go/whisper code)

# Possible solutions
See acceptance criteria.

# Notes
-

**Comment by oskarth** [comment]
Blocked by https://github.com/vacp2p/specs/issues/27

**Comment by oskarth** [comment]
See https://github.com/vacp2p/pm/issues/7 https://github.com/status-im/specs/issues/73

**Comment by oskarth** [comment]
How is this issue going @samyoul?

cc @andremedeiros

**Comment by Samyoul** [comment]
Hey. I'll have a PR for this by the end of the day.

**Comment by Samyoul** [comment]
@oskarth , the initial rewrite PR draft will not be ready today, there are too many refs to outdated things, or things that are sort of relevant or things that need further research to see if there are Waku analogous versions of Whisper terminology etc.

I will open a draft PR of what I've started, reference it here, and I'll keep adding to it until it is complete ready for review. I naively thought it would be a mostly find and replace job. Most of it is, the minority that will take time, isn't.

**Comment by Samyoul** [comment]
This is the draft https://github.com/status-im/specs/pull/114

**Comment by Samyoul** [comment]
Finally merged https://github.com/status-im/specs/pull/114
