### ISSUE TITLE
Implementation matrix for Whisper/Waku clients

### ISSUE THREAD

**Issue by decanus** [status-im/specs#63]
## Problem

What it means to support Whisper/Waku isn't clear, as there are many different components of it. Geth/nimbus/parity should be added to spec of where lightnode implementation exists for waku

## Details
Dimensions to capture:
- [x] light mode
- [x] mailserver server
- [x] mailserver client
- [x] shh/6
- [x] waku/0

Code bases (with relevant version number / commit hash of need be):
- [x] geth
- [x] status whisper
- [ ] parity
- [x] nim-eth
- [ ] javascript? (Embark)

## Acceptance criteria

- [ ] Matrix with implementation Status of all dimensions and implementations
- [ ] It can be a WIP, so acceptance criteria OK to have empty rows, etc.

**Comment by oskarth** [comment]
Can turn this (issue, then matrix) into a checklist, corresponding with each capability and client version. E.g.

Dimensions:
light mode
mailserver server
mailserver client
shh/6
waku/0

Code bases (with relevant version number / commit hash of need be):
geth
status whisper
parity
nim-eth
javascript? (Embark)

It can be a WIP, so acceptance criteria OK to have empty rows, etc.

Any other dimensions? @kdeme @adambabik

**Comment by decanus** [comment]
so by the looks of it @oskarth, parity doesn't seem to include whisper anymore. However I did find this: https://github.com/paritytech/parity/pull/7421, no idea what the state of that is, hence I suggest we drop parity from the list.

**Comment by decanus** [comment]
@oskarth https://notes.status.im/sWRbsbX4QjuNE5f3BAvHBw?both here is a start to the matrix. Would be good if someone else had a look, once that is done we can add it to the repo.

**Comment by oskarth** [comment]
Looks good, I think we can merge this as is (first PR). Where should we put it? By default I'd put it in the main Status client spec under a section "Implementation Matrix" or so.

**Comment by decanus** [comment]
@oskarth what is the right place for the matrix?

**Comment by oskarth** [comment]
Either Vac Waku spec implementation status append, or Status main client spec

**Comment by oskarth** [comment]
@decanus what's the state of this issue?

**Comment by decanus** [comment]
@oskarth done.
