### ISSUE TITLE
The road to V1 specs and more

### ISSUE THREAD

**Issue by corpetty** [status-im/specs#65]
Alright, this issue is a to track and describe what needs to be done to get to the start of V1 specs.  For V1, I'm ok with the first non-draft version having overlap with specs that live in vacp2p specs. As things finalize there, we can remove them here and appropriately reference them here with our design decisions around that reference. 

I'd also like to store various higher-level views of the Status App here which give insight to how our implementation of Status uses the specs within here.  I'm open to how we document and store that, but initial attempts to do so can be found here:
- [Message Encapsulation Structure](https://miro.com/app/board/o9J_kwCj62U=/)
- [Front-end / Back-end Comms flow](https://miro.com/app/board/o9J_kwBIwto=/)
- [Message lifecycle](https://notes.status.im/tSXcFBDuTLy7IvIyIh5WBQ#)

### Checklist of getting the bare minimums for V1:
- [x] [Draft Status Client Spec](https://github.com/status-im/specs/blob/master/status-client-spec.md) -> SIP 1
  - WIP PR here https://github.com/status-im/specs/pull/76
- [x] [Draft Secure Transport Spec](https://github.com/status-im/specs/blob/master/status-secure-transport-spec.md) -> SIP x
- [ ]  [Draft Payload Spec](https://github.com/status-im/specs/blob/master/status-payloads-spec.md) -> SIP x
  - [x] resolve https://github.com/status-im/specs/issues/62
  - [ ] resolve https://github.com/status-im/specs/issues/57 PR open
- [ ] [Draft Account spec](https://github.com/status-im/specs/blob/master/status-account-spec.md) -> SIP x
- [x] [Draft Whisper Usage Spec](https://github.com/status-im/specs/blob/master/status-whisper-usage-spec.md) -> SIP x
  - [x] resolve https://github.com/status-im/specs/issues/59
  - [x] resolve https://github.com/status-im/specs/issues/58
- [ ] [Draft Whipser Mailserver spec](https://github.com/status-im/specs/blob/master/status-whisper-mailserver-spec.md) -> SIP x
  - [x] resolve https://github.com/status-im/specs/issues/55

Note that this does not HAVE to be done before V1 launch, but with the extra time between finishing required issues and launch date, it should give some time on documenting how V1 works.

Hit me with updates, changes, and thoughts.

**Comment by oskarth** [comment]
@corpetty can we update the state of this?

**Comment by oskarth** [comment]
Taking this over. See open PRs here https://github.com/status-im/specs/pulls

**Comment by oskarth** [comment]
Bare minimum done!
